#!/usr/bin/env python3
if __name__ == "__main__":
    import sys
    import pointer_cli
    try:
        pointer_cli.Pointer_CLI().initFromArgv()
    except (KeyboardInterrupt, SystemExit):
        print("\nInterrupted...", file=sys.stderr)
    except pointer_cli.PointerRuntimeError as e:
        sys.exit(e)
